from pydantic import BaseModel, Field, model_validator


class GeneratedQuestion(BaseModel):
    """Represent a question generated by Gemini."""

    question_title: str
    question_options: list[str] = Field(min_length=4, max_length=4)
    answer: str

    @model_validator(mode="after")
    def validate_answer(self):
        """Ensure the answer matches one option."""
        if self.answer not in self.question_options:
            raise ValueError("Answer must match one question option.")
        return self


class GeneratedQuiz(BaseModel):
    """Represent a complete quiz generated by Gemini."""

    title: str
    description: str
    questions: list[GeneratedQuestion] = Field(
        min_length=10,
        max_length=10,
    )
